spring.oauth2.resource:
  id: cloud_controller
  jwt:
    keyUri: ${vcap.services.sso.credentials.tokenKey}

logging:
  level:
    nats.client: DEBUG
    org.springframework.security: DEBUG
    org.trustedanalytics.les: DEBUG

services:
  api:
    url: ${vcap.services.sso.credentials.apiEndpoint}

  store:
    serverName: ${vcap.services.latest-events-store.credentials.hostname:localhost}
    serverPort: ${vcap.services.latest-events-store.credentials.port:27017}
    dbName: ${vcap.services.latest-events-store.credentials.dbname:les}
    user: ${vcap.services.latest-events-store.credentials.username:}
    password: ${vcap.services.latest-events-store.credentials.password:}

nats.connection: ${vcap.services.nats-provider.credentials.url:nats://localhost:4222}

endpoints.enabled: false
endpoints.health.enabled: true
